# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a47d7f4a65fdd53da5058f815993fb797def2cee231eee3e84bc8002706645d302c26b2436eca04e3703f4d0d9ac065999c1095b3454475459846bc7dadd5494

test:
  secret_key_base: 9cb73dbf9252141d350c01816b2f08d86cec2503be0dfa64a4f3e629930a97a9c981724f559b84370827ea061f12a46cb05704138bb2671418a45a5adda2e3a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
